# title of website
title: æ•°æ®æ³•å¸¸ç”¨å·¥å…·

# description of website
description: haorenzhou's navigation site

# favicon of website
favicon: "https://github.com/haorenzhou.png?size=40"

# your website url
url: https://haorenzhou.github.io/haorenzhou.github.io/

# github profile url
github: "https://github.com/haorenzhou"

# footer message
footer: Â© 2023 @DLaw Hub

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # å¯é€‰çš„æœç´¢å¼•æ“
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: èµ„è®¯åº”ç”¨
      sites:
        - name: DataGuidance
          description: ã€è‹±æ–‡ã€‘æ¯æ—¥è¿½è¸ªå…¨çƒæ•°æ®æ³•ç›¸å…³çš„æ–°é—»èµ„è®¯æ¦‚è¦ï¼›å°‘é‡å…è´¹è¯•ç”¨æ¬¡æ•°
          url: https://www.dataguidance.com/search/news
        - name: Iapp news
          description: ã€è‹±æ–‡ã€‘æ¯æ—¥æ–°é—»æ¦‚è§ˆï¼›èµ„è®¯å…¨å…è´¹ï¼›æœ‰åŸæ–‡é“¾æ¥ã€‚
          url: https://iapp.org/news
        - name: GenAIs - AICGå‘¨æŠ¥
          description: å¯å…³æ³¨å…¬ä¼—å·â€œGenAIsâ€ä¸­çš„AICGå‘¨æŠ¥æ ç›®ï¼Œè¯¥æ ç›®æ¯å‘¨ä¼šå‘å¸ƒAICGè¡Œä¸šçš„è®¯æ¯ã€‚
    - name: æ•°æ®æ³•è§„ç½‘ç«™
      sites:
        - name: æ•°æ®ä¿æŠ¤ç‰ˆå›¾é¡¹ç›® Data Protection Mapping Project
          description: ç”¨æ•°æ®æµçš„æ–¹å¼å±•ç¤ºäº†å„å›½è§„åˆ™ä¹‹é—´çš„è”ç³»ä¸ä¸åŒï¼Œå¾ˆç›´è§‚ã€‚å¯ä»¥é€æ¡å¯¹æ¯”å„ä¸»è¦æ•°æ®æ³•ä¹‹é—´çš„å·®å¼‚å’Œå¯¹åº”å…³ç³»ã€‚
          url: https://www.dpmap.org/#/dashboard
        - name: EUR- Lexæ³•å¾‹åº“
          description: å¯ä»¥æ£€ç´¢æ¬§ç›Ÿçš„æ³•å¾‹æ–‡æœ¬å’Œåˆ¤ä¾‹
          url: https://eur-lex.europa.eu/homepage.html
        - name: æ¬§ç›Ÿã€è‹±å›½ä»¥åŠå¾·å›½çš„æ•°å­—ç«‹æ³•è¿›å±•è¿½è¸ªå™¨
          description: å¾·å›½ç™¾å¹´è€ç‰Œå¾‹æ‰€Taylor Wessingè®¾è®¡äº†ä¸€æ¬¾appï¼Œè¿½è¸ªæ¬§ç›Ÿã€è‹±å›½ä»¥åŠå¾·å›½çš„æ•°å­—ç«‹æ³•è¿›å±•ã€‚
          url: https://www.taylorwessing.com/en/online-services/digital-legislation-tracker?utm_source=LinkedIn&utm_medium=social&utm_content=Tool&utm_campaign=UK-DLT-210323
    - name: å…¶ä»–æ³•è§„ç½‘ç«™
      sites:
        - name: å…¨çƒæ³•è§„ç½‘
          description: å…¨çƒæ³•è§„ç½‘æ˜¯å•†åŠ¡éƒ¨å®˜ç½‘é¡¹ä¸‹çš„å¤–å›½æ³•å¾‹æ³•è§„èµ„æºåº“ï¼Œæ”¿åºœå®˜æ–¹å‡ºå“çš„é«˜è´¨é‡æ³•è§„åº“ï¼Œå¯ä»¥å¸®åŠ©å¤§å®¶å¿«é€Ÿæ— ç—›æ£€ç´¢å¤–å›½æ³•å¾‹æ³•è§„ã€‚å¢ƒå¤–æ³•æ¡ã€å›½é™…æ¡çº¦éƒ½æ”¯æŒæ ‡é¢˜åŠå…¨æ–‡æ£€ç´¢ï¼›æ³•æ¡å‡ä¸ºå®˜æ–¹ä¸­æ–‡è¯‘æ–‡ï¼Œå¹¶é™„æœ‰åŸæ–‡é“¾æ¥ï¼›æ³•è§„æ³•æ¡éƒ½æŒ‰ç…§å›½åˆ«åŠåœ°åŒºè¿›è¡Œäº†åˆ†ç±»ï¼Œä¾¿äºå¿«é€Ÿæ£€ç´¢ã€‚
          url: http://policy.mofcom.gov.cn/claw/
        - name: Oslawå°½èŒè°ƒæŸ¥ç½‘å€å¯¼èˆª
          description: æœ€å…¨é¢çš„æ³•å¾‹ç±»ç½‘å€å¯¼èˆªï¼Œæ¶µç›–äº†å„ç§ä¸šåŠ¡åœºæ™¯ä¸‹ä¼šä½¿ç”¨åˆ°çš„ç½‘é¡µã€‚
          url: http://www.oslaw.net/c
        - name: å…¨å›½è®¤è¯è®¤å¯ä¿¡æ¯å…¬å…±æœåŠ¡å¹³å°
          description: è¿™ä¸ªå¹³å°å¯ä»¥æŸ¥è¯¢åˆ°ç®¡ç†ä½“ç³»ã€æœåŠ¡ã€äº§å“ç­‰è®¤è¯ä¿¡æ¯ï¼Œå¸®åŠ©ä¼ä¸šæ ¸å®ç›¸å¯¹æ–¹çš„è¯ä¹¦çœŸå®æ€§ã€‚
          url: http://cx.cnca.cn/CertECloud/index/index/page
        - name: å¯¹å¤–æŠ•èµ„åˆä½œå›½åˆ«ï¼ˆåœ°åŒºï¼‰æŒ‡å—
          description: å•†åŠ¡éƒ¨ç¼–åˆ¶çš„æŒ‡å—ï¼Œæ¶µç›–äº†æ‰€åœ¨å›½æ”¿æ²»ã€ç»æµã€ç¤¾ä¼šç­‰å¤šæ–¹é¢å†…å®¹ï¼Œä¹ŸåŒ…å«äº†å½“åœ°çš„æ³•å¾‹åˆ¶åº¦ã€‚
          url: http://fec.mofcom.gov.cn/article/gbdqzn/
        - name: ä¸Šæµ·å›½é™…ç»è´¸åˆè§„æ³•å¾‹æœåŠ¡å¹³å¹³å°
          description: åŒ…å«äº†å›½é™…ç»è´¸ç›¸å…³çš„åˆ¶è£ã€æ•°æ®ã€æ³•è§„ã€æœåŠ¡ç­‰å†…å®¹ã€‚
          url: https://www.jmhg.sh.cn/
        - name: ç¾å›½å„ç±»åˆ¶è£æ¸…å•çš„ç»¼åˆå¯¼èˆªå…¥å£ï¼ˆCSLï¼‰
          description: åŒ…å«äº†å‡ºå£ç®¡åˆ¶ã€ä¸€ç±»åˆ¶è£ã€äºŒç±»åˆ¶è£ç­‰ç¾å›½å„éƒ¨é—¨å‘å¸ƒçš„åˆ¶è£æ¸…å•ã€‚
          url: https://www.trade.gov/consolidated-screening-list
    - name: å›½å¤–æ³•å¾‹åˆ¶åº¦ä»‹ç»
      sites:
        - name: DLA Piper Global Data Protection Laws of the World
          description: ã€è‹±æ–‡ã€‘DLA Piperå¾‹æ‰€å¯¹å…¨çƒå„å›½æ•°æ®æ³•çš„æ¢³ç†ä¸æ±‡æ€»ã€‚
          url: https://www.dlapiperdataprotection.com/index.html?t=about&c=IN
        - name: Linklaters  Data Protected
          description: ã€è‹±æ–‡ã€‘Linklaterså¾‹æ‰€å¯¹å…¨çƒæ•°æ®æ³•å¾‹åˆ¶åº¦å’Œç›¸å…³æ¦‚å¿µçš„æ¢³ç†ã€‚
          url: https://www.linklaters.com/en/insights/data-protected/data-protected-glossary
        - name: Baker Mckenzie Global Data Privacy & Security Handbook 
          description: ã€è‹±æ–‡ã€‘Baker Mckenzieå¾‹æ‰€çš„æ¢³ç†ï¼›å„å›½æ³•å¾‹æ³•è§„çš„æ¢³ç†è¾ƒä¸ºå…¨é¢ã€‚
          url: https://resourcehub.bakermckenzie.com/en/resources/data-privacy-security/latin-america/argentina/topics/regulators-and-enforcement-priorities
        - name: DataGuidance Jurisdiction
          description: DataGuidanceç½‘ç«™å¯¹å„å›½åˆ¶åº¦ã€æ–°é—»ã€è¯„è®ºæ–‡ç« çš„æ±‡æ€»ã€‚æ³•å¾‹åˆ¶åº¦çš„ä»‹ç»è¾ƒä¸ºç®€å•ã€‚
          url: https://www.dataguidance.com/jurisdiction/african-bodies
        - name: DataGuidance Jurisdiction
          description: DataGuidanceç½‘ç«™å¯¹å„å›½åˆ¶åº¦ã€æ–°é—»ã€è¯„è®ºæ–‡ç« çš„æ±‡æ€»ã€‚æ³•å¾‹åˆ¶åº¦çš„ä»‹ç»è¾ƒä¸ºç®€å•ã€‚
          url: https://www.dataguidance.com/jurisdiction/african-bodies
    - name: æ¬§æ´²æ•°æ®ä¿æŠ¤æœºæ„å®˜ç½‘
      sites:
        - name: ğŸ‡ªğŸ‡ºæ¬§ç›Ÿå„æˆå‘˜å›½æ•°æ®ä¿æŠ¤æœºæ„é›†åˆ
          description: åˆ—ä¸¾äº†æ¬§ç›Ÿæˆå‘˜å›½æ•°æ®ä¿æŠ¤æœºæ„çš„æ¸…å•å’Œç®€å•ä¿¡æ¯ã€‚
          url: https://edpb.europa.eu/about-edpb/about-edpb/members_en/
        - name: ğŸ‡·ğŸ‡ºä¿„ç½—æ–¯ï¼ˆRoskomnadzorï¼‰
          description: ä¿„ç½—æ–¯è”é‚¦é€šä¿¡ã€ä¿¡æ¯æŠ€æœ¯å’Œå¤§ä¼—ä¼ åª’ç›‘ç£å±€å®˜ç½‘
          url: https://eng.rkn.gov.ru/
        - name: ğŸ‡µğŸ‡±æ³¢å…°ï¼ˆUODOï¼‰
          description: æ³¢å…°æ•°æ®ä¿æŠ¤æœºæ„å®˜ç½‘
          url: https://uodo.gov.pl/
        - name: ğŸ‡­ğŸ‡·å…‹ç½—åœ°äºšï¼ˆazopï¼‰
          description: å…‹ç½—åœ°äºšæ•°æ®ä¿æŠ¤æœºæ„å®˜ç½‘
          url: https://azop.hr/
        - name: ğŸ‡¨ğŸ‡¿æ·å…‹ï¼ˆuoouï¼‰
          description: æ·å…‹æ•°æ®ä¿æŠ¤æœºæ„å®˜ç½‘
          url: https://www.uoou.cz/
        - name: ğŸ‡¬ğŸ‡·å¸Œè…Šï¼ˆHellenic Data Protection Authorityï¼‰
          description: å¸Œè…Šæ•°æ®ä¿æŠ¤æœºæ„å®˜ç½‘
          url: https://www.dpa.gr/
        - name: ğŸ‡­ğŸ‡ºåŒˆç‰™åˆ©ï¼ˆNAIHï¼‰
          description: åŒˆç‰™åˆ©æ•°æ®ä¿æŠ¤æœºæ„å®˜ç½‘
          url: https://www.naih.hu/
        - name: ğŸ‡¦ğŸ‡¹å¥¥åœ°åˆ©ï¼ˆdsbï¼‰
          description: å¥¥åœ°åˆ©æ•°æ®ä¿æŠ¤æœºæ„å®˜ç½‘
          url: https://www.dsb.gv.at/
        - name: ğŸ‡©ğŸ‡°ä¸¹éº¦ï¼ˆDatatilsynetï¼‰
          description: ä¸¹éº¦æ•°æ®ä¿æŠ¤æœºæ„å®˜ç½‘
          url: https://www.datatilsynet.dk/
        - name: ğŸ‡«ğŸ‡®èŠ¬å…°ï¼ˆOffice of the Data Protection Ombudsmanï¼‰
          description: èŠ¬å…°æ•°æ®ä¿æŠ¤æœºæ„å®˜ç½‘
          url: https://tietosuoja.fi/en/home
        - name: ğŸ‡¸ğŸ‡ªç‘å…¸ï¼ˆIMYï¼‰
          description: ç‘å…¸æ•°æ®ä¿æŠ¤æœºæ„å®˜ç½‘
          url: https://www.imy.se/
        - name: ğŸ‡³ğŸ‡´æŒªå¨ï¼ˆDatatilsynetï¼‰
          description: æŒªå¨æ•°æ®ä¿æŠ¤æœºæ„å®˜ç½‘
          url: https://www.datatilsynet.no/
        - name: ğŸ‡®ğŸ‡¸å†°å²›ï¼ˆPersÃ³nuverndï¼‰
          description: å†°å²›æ•°æ®ä¿æŠ¤æœºæ„å®˜ç½‘
          url: https://www.personuvernd.is/
        - name: ğŸ‡©ğŸ‡ªå¾·å›½ï¼ˆBFDIï¼‰
          description: å¾·å›½æ•°æ®ä¿æŠ¤æœºæ„å®˜ç½‘
          url: https://www.bfdi.bund.de/DE/Home/home_node.html
        - name: ğŸ‡®ğŸ‡¹æ„å¤§åˆ©ï¼ˆGPDPï¼‰
          description: æ„å¤§åˆ©æ•°æ®ä¿æŠ¤æœºæ„å®˜ç½‘
          url: https://www.garanteprivacy.it/
        - name: ğŸ‡§ğŸ‡ªæ¯”åˆ©æ—¶ï¼ˆ(APD-GBA)
          description: æ¯”åˆ©æ—¶æ•°æ®ä¿æŠ¤æœºæ„å®˜ç½‘
          url: https://www.dataprotectionauthority.be/citizen
        - name: ğŸ‡±ğŸ‡ºå¢æ£®å ¡ï¼ˆCNPDï¼‰
          description: å¢æ£®å ¡æ•°æ®ä¿æŠ¤æœºæ„å®˜ç½‘
          url: https://cnpd.public.lu/fr.html
        - name: ğŸ‡³ğŸ‡±è·å…°ï¼ˆAutoriteit Persoonsgegevensï¼‰
          description: è·å…°æ•°æ®ä¿æŠ¤æœºæ„å®˜ç½‘
          url: https://autoriteitpersoonsgegevens.nl/
        - name: ğŸ‡«ğŸ‡·æ³•å›½ï¼ˆCNILï¼‰
          description: æ³•å›½æ•°æ®ä¿æŠ¤æœºæ„å®˜ç½‘
          url: https://www.cnil.fr/en/contact-us
        - name: ğŸ‡ªğŸ‡¸è¥¿ç­ç‰™ï¼ˆAEPDï¼‰
          description: è¥¿ç­ç‰™æ•°æ®ä¿æŠ¤æœºæ„å®˜ç½‘
          url: https://www.aepd.es/es
        - name: ğŸ‡µğŸ‡¹è‘¡è„ç‰™ï¼ˆCNPDï¼‰
          description: è‘¡è„ç‰™æ•°æ®ä¿æŠ¤æœºæ„å®˜ç½‘
          url: https://www.cnpd.pt/
        - name: ğŸ‡®ğŸ‡ªçˆ±å°”å…°ï¼ˆDPCï¼‰
          description: çˆ±å°”å…°æ•°æ®ä¿æŠ¤æœºæ„å®˜ç½‘
          url: https://www.dataprotection.ie/
    - name: äºšå¤ªåœ°åŒºæœºæ„å®˜ç½‘
      sites:
        - name: ğŸ‡­ğŸ‡°ä¸­å›½é¦™æ¸¯
          description: ä¸­å›½é¦™æ¸¯å€‹äººè³‡æ–™ç§éš±å°ˆå“¡å…¬ç½²å®˜ç½‘
          url: https://www.pcpd.org.hk/
        - name: ğŸ‡²ğŸ‡´ä¸­å›½æ¾³é—¨
          description: ä¸­å›½æ¾³é—¨å€‹äººè³‡æ–™ä¿è­·è¾¦å…¬å®¤å®˜ç½‘
          url: https://www.gpdp.gov.mo/
        - name: ä¸­å›½å°æ¹¾
          description: ä¸­å›½å°æ¹¾å€‹äººè³‡æ–™ä¿è­·å°ˆæ¡ˆè¾¦å…¬å®¤å®˜ç½‘
          url: https://pipa.ndc.gov.tw/
        - name: ğŸ‡°ğŸ‡·éŸ©å›½
          description: éŸ©å›½ä¸ªäººä¿¡æ¯ä¿æŠ¤å§”å‘˜ä¼šå®˜ç½‘
          url: https://www.privacy.go.kr/
        - name: ğŸ‡¯ğŸ‡µæ—¥æœ¬ï¼ˆPPCï¼‰
          description: æ—¥æœ¬æ•°æ®ä¿æŠ¤æœºæ„å®˜ç½‘
          url: https://www.ppc.go.jp/en/
        - name: ğŸ‡®ğŸ‡©å°åº¦å°¼è¥¿äºšï¼ˆMinistry of Communication and Informaticsï¼‰
          description: å°åº¦å°¼è¥¿äºšä¿¡æ¯ä¸é€šè®¯éƒ¨å®˜ç½‘
          url: https://www.kominfo.go.id/
        - name: ğŸ‡²ğŸ‡¾é©¬æ¥è¥¿äºšï¼ˆPDPCï¼‰
          description: é©¬æ¥è¥¿äºšæ•°æ®ä¿æŠ¤æœºæ„å®˜ç½‘
          url: https://www.pdp.gov.my/jpdpv2/?lang=en
        - name: ğŸ‡¸ğŸ‡¬æ–°åŠ å¡ï¼ˆPDPCï¼‰
          description: æ–°åŠ å¡æ•°æ®ä¿æŠ¤æœºæ„å®˜ç½‘
          url: https://www.pdpc.gov.sg/
        - name: ğŸ‡®ğŸ‡³å°åº¦ï¼ˆMeitYï¼‰
          description: å°åº¦ç”µå­ä¿¡æ¯æŠ€æœ¯éƒ¨å®˜ç½‘
          url: https://www.meity.gov.in/
        - name: ğŸ‡µğŸ‡°å·´åŸºæ–¯å¦
          description: å·´åŸºæ–¯å¦ä¿¡æ¯æŠ€æœ¯ä¸ç”µä¿¡éƒ¨å®˜ç½‘
          url: https://moitt.gov.pk/
        - name: ğŸ‡µğŸ‡­è²å¾‹å®¾ï¼ˆNPCï¼‰
          description: è²å¾‹å®¾æ•°æ®ä¿æŠ¤æœºæ„å®˜ç½‘
          url: https://www.privacy.gov.ph/
        - name: ğŸ‡¦ğŸ‡ºæ¾³å¤§åˆ©äºšï¼ˆOAICï¼‰
          description: æ¾³å¤§åˆ©äºšéšç§ä¸“å‘˜åŠå…¬å®¤å®˜ç½‘
          url: https://www.oaic.gov.au/       
    - name: ä¸­ä¸œåœ°åŒºæœºæ„å®˜ç½‘
      sites:
        - name: ğŸ‡¸ğŸ‡¦æ²™ç‰¹ï¼ˆNDMOï¼‰
          description: æ²™ç‰¹å›½å®¶æ•°æ®ç®¡ç†åŠå…¬å®¤å®˜ç½‘
          url: https://www.cnil.fr/
        - name: ğŸ‡¸ğŸ‡¦æ²™ç‰¹ï¼ˆSDAIAï¼‰
          description: æ²™ç‰¹æ•°æ®å’Œäººå·¥æ™ºèƒ½ç®¡ç†å±€å®˜ç½‘
          url: https://sdaia.gov.sa/
    - name: ç¾æ´²åœ°åŒºæ„å®˜ç½‘
      sites:
        - name: ğŸ‡¨ğŸ‡¦åŠ æ‹¿å¤§ï¼ˆOPCï¼‰
          description: åŠ æ‹¿å¤§éšç§ä¸“å‘˜åŠå…¬å®¤å®˜ç½‘
          url: https://www.priv.gc.ca/
        - name: ğŸ‡§ğŸ‡·å·´è¥¿ï¼ˆANPDï¼‰
          description: å·´è¥¿æ•°æ®ä¿æŠ¤æœºæ„å®˜ç½‘
          url: https://www.gov.br/anpd/pt-br
        - name: ğŸ‡¨ğŸ‡´å“¥ä¼¦æ¯”äºšï¼ˆSICï¼‰
          description: å“¥ä¼¦æ¯”äºšå·¥å•†ç›‘ç®¡å±€å®˜ç½‘
          url: https://www.sic.gov.co/
    - name: å®ç”¨å·¥å…·
      sites:
        - name: ITDOG
          description: å¯ä»¥æŸ¥è¯¢dnsï¼Œè¿›è¡Œç½‘ç«™æµ‹é€Ÿï¼Œçœ‹çœ‹å“ªäº›ç½‘ç«™è¢«å°äº†ï¼Œhh
          url: https://www.itdog.cn/
        - name: è¯­æ³•æ£€æŸ¥å·¥å…· Grammarly
          description: å¸®åŠ©æ£€æŸ¥æ–‡ç« ä¸­çš„è¯­æ³•é”™è¯¯ã€‚åŸºç¡€ç‰ˆå…è´¹ä½¿ç”¨ã€‚
          url: https://www.grammarly.com/office-addin/downloading/mac
        - name: çŸ¥äº‘æ–‡çŒ®ç¿»è¯‘
          description: å¾ˆå¥½çš„ç¿»è¯‘è½¯ä»¶ï¼Œè¾¹é˜…è¯»è¾¹ç¿»è¯‘ã€‚
          url: https://www.yuque.com/xtranslator/zy/wv60oc
        - name: Xtranslator è‹±æ–‡æ–‡çŒ®ç¿»è¯‘è½¯ä»¶
          description: çŸ¥äº‘å›¢é˜Ÿ2020å¹´å‡ºå“äº†ä¸€æ¬¾æ–°çš„è½¯ä»¶å«åšXtranslatorï¼Œå¯ä»¥é…åˆè‡ªå·±å–œæ¬¢çš„PDFé˜…è¯»å™¨ä½¿ç”¨ã€‚
          url: https://www.yuque.com/xtranslator/help/xzzu1f
        - name: ï¼ˆMailMasterï¼‰AIé‚®ä»¶ç”Ÿæˆ
          description: AIå¸®åŠ©ä½ è‡ªåŠ¨ç”Ÿæˆæ‰€éœ€è¦çš„é‚®ä»¶æ­£æ–‡ã€‚æ”¯æŒä¸­æ–‡è¾“å…¥å’Œè¾“å‡ºã€‚
          url: https://mailmaster.ai/#/writeAndRes
    - name: å®˜æ–¹å…¬ä¼—å·æ¨è
      sites:
        - name: ç½‘ä¿¡ä¸­å›½
          description: å›½å®¶ç½‘ä¿¡åŠå®˜æ–¹è´¦å·
        - name: å…¬å®‰éƒ¨ç½‘å®‰å±€
          description: å…¬å®‰éƒ¨ç½‘å®‰å±€å®˜æ–¹è´¦å·
        - name: å…¬å®‰éƒ¨ç½‘ç»œå®‰å…¨ç­‰çº§ä¿æŠ¤ä¸­å¿ƒ
          description: å…¬å®‰éƒ¨ç¬¬ä¸‰ç ”ç©¶æ‰€å¼€å±•ç­‰çº§ä¿æŠ¤çš„å®˜æ–¹è´¦å·
        - name: å…¬å®‰ä¸‰æ‰€ç½‘ç»œå®‰å…¨æ³•å¾‹ç ”ç©¶ä¸­å¿ƒ
          description: å…¬å®‰éƒ¨ç¬¬ä¸‰ç ”ç©¶æ‰€å®˜æ–¹è´¦å·
        - name:  CAICTäº’è”ç½‘æ³•å¾‹ç ”ç©¶ä¸­å¿ƒ
          description: ä¸­å›½ä¿¡æ¯é€šä¿¡ç ”ç©¶é™¢å®˜æ–¹è´¦å·
        - name: ä¸­å›½ä¿¡é€šé™¢CAICT
          description: ä¸­å›½ä¿¡æ¯é€šä¿¡ç ”ç©¶é™¢å®˜æ–¹è´¦å·
        - name: CCIAæ•°æ®å®‰å…¨å·¥ä½œå§”å‘˜ä¼š
          description: éå¸¸å¤šå¯¹æ•°æ®åˆè§„æ ‡å‡†çš„è§£è¯»ï¼Œè´¨é‡å¾ˆé«˜ã€‚          
    - name: å®åŠ¡ç±»å…¬ä¼—å·æ¨è
      sites:
        - name: é€æ³•ä¸Šç½‘
          description: æ±‡ä¸šå²å®‡èˆªå¾‹å¸ˆçš„ä¸ªäººå…¬ä¼—å·ã€‚æ›´æ–°é€Ÿåº¦éå¸¸å¿«ï¼Œè¡Œæ–‡ä¹Ÿé€šä¿—æ˜“æ‡‚ï¼Œå¯è¯»æ€§éå¸¸å¼ºã€‚
        - name: TMTæ³•å¾‹è®ºå›
          description: ä¸­ä¼¦é™ˆé™…çº¢å¾‹å¸ˆå›¢é˜Ÿçš„å…¬ä¼—å·ã€‚æ›´æ–°å¿«ï¼Œå¹²è´§å¾ˆå¤šã€‚
          url: http://dunnnk.com/
        - name: Graphberry
          description: Free design resources, Mockups, PSD web templates, Icons
          url: http://www.graphberry.com/
        - name: ä¸ªäººä¿¡æ¯ä¸æ•°æ®ä¿æŠ¤å®åŠ¡è¯„è®º
          description: å¤§æˆæˆ´å»ºæ°‘å¾‹å¸ˆå’Œé‚“å¿—æ¾å¾‹å¸ˆå›¢é˜Ÿçš„å…¬ä¼—å·ï¼Œæ—¥å¸¸ä¼šæ‘˜ç¼–æ•°æ®åˆè§„ç›¸å…³çš„èµ„è®¯ï¼ŒåŸŸå†…å¤–éƒ½æœ‰è´¨é‡éƒ½ä¸é”™ï¼Œä¹Ÿä¼šæœ‰è‡ªå·±çš„åŸåˆ›è§£è¯»ã€‚
        - name: ç½‘ç»œæ³•å®åŠ¡åœˆ
          description: å¦ä¸å¾‹å¸ˆäº‹åŠ¡æ‰€çš„å®˜æ–¹å…¬ä¼—å·ã€‚æ¶‰çŒçš„é¢†åŸŸä¼šæ¯”æ•°æ®åˆè§„æ›´åŠ å¹¿æ³›ä¸€äº›ï¼Œæ¨æ–‡è´¨é‡ä¹Ÿä¸é”™ã€‚
        - name: å‡ºæµ·äº’è”ç½‘æ³•å¾‹è§‚å¯Ÿ
          description: å¦ä¸ç‹æ·å¾‹å¸ˆå›¢é˜Ÿçš„å…¬ä¼—å·ã€‚ä¸»è¦å…³æ³¨åŸŸå¤–æ•°æ®åˆè§„åŠ¨æ€ã€‚æ•°æ®å‡ºå¢ƒ100é—®å¹²è´§çœŸçš„å¾ˆå¤šã€‚
        - name: Cä½æ•°æ®è°ˆ
          description: åè¯šå´æœˆç´å¾‹å¸ˆå›¢é˜Ÿçš„å…¬ä¼—å·ã€‚æ–°è§„è§£è¯»çš„é€Ÿåº¦ä¹Ÿå¾ˆå¿«ï¼Œå¹¶ä¸”æœ‰æ—¶å€™ä¼šä»¥å›¾è§£çš„æ–¹å¼ç›´è§‚å±•ç¤ºã€‚
        - name: äº’è”ç½‘åˆè§„å›
          description: äº¬è¡¡å¼ è±ªå¾‹å¸ˆå›¢é˜Ÿçš„å…¬ä¼—å·ã€‚å¯¹æ•°æ®åˆè§„ç›¸å…³çš„åˆ‘äº‹è¯‰è®¼å¾ˆæœ‰ç ”ç©¶ï¼Œå¹¶ä¼šä¸å®šæœŸä¸¾åŠçº¿ä¸‹æ´»åŠ¨ã€‚
        - name: ç½‘æ•°æ³•å®¤
          description: ç«å¤©å…¬è¯šè¢ç«‹å¿—å¾‹å¸ˆçš„å…¬ä¼—å·ã€‚è¡Œæ–‡å¤§é“è‡³ç®€ã€è¦è¨€ä¸çƒ¦ï¼Œå¯ä»¥é ç€çŸ­çŸ­å‡ ç™¾å­—è®²æ¸…æ¥šéå¸¸å¤æ‚çš„é—®é¢˜ã€‚
        - name: æ™ºèƒ½æ™’å®¢
          description: é‡‘è¯šåŒè¾¾å½­å‡¯å¾‹å¸ˆå›¢é˜Ÿçš„å…¬ä¼—å·ã€‚æ¯ä¸ªæœˆä¼šå®šæœŸæ›´æ–°æ•°æ®åˆè§„çš„æœˆæŠ¥åŒæ—¶æ¨èç›¸å…³çº¿ä¸Šçº¿ä¸‹æ´»åŠ¨ã€‚
        - name: ç½‘ç»œä¸æ•°æ®æ³•å¾‹äº‹åŠ¡
          description: æ±‡ä¸šæ•°æ®åˆè§„å›¢é˜Ÿçš„å…¬ä¼—å·ï¼Œé»„æ˜¥æ—å¾‹å¸ˆå¾ˆå¤šéå¸¸æœ‰å¹²è´§çš„æ–°è§„è§£è¯»éƒ½ä¼šå‘åœ¨è¿™é‡Œã€‚
        - name: æ•°æ®åˆè§„ä¸æ²»ç†
          description: å¼ æ™“ä¸½ï¼Œå°±èŒäºæŸå¤§å‹äº’è”ç½‘ä¼ä¸šï¼Œä»äº‹æµ·å¤–ä¸šåŠ¡çš„éšç§ä¿æŠ¤å·¥ä½œã€‚æ„è§é¢†è¢–ï¼Œå¸¸æå‡ºæ–°æ½®çš„è¯é¢˜å¹¶æå‡ºè‡ªå·±çš„è§‚ç‚¹ã€‚
    - name: å­¦æœ¯ç±»å…¬ä¼—å·æ¨è
      sites:
        - name: ç½‘å®‰å¯»è·¯äºº
          description: åŒ—ç†å·¥æ´ªå»¶é’è€å¸ˆçš„å…¬ä¼—å·ï¼Œå¾ˆå¤šåŸŸå¤–æ³•è§„çš„ç¿»è¯‘ä»¥åŠå¢ƒå†…æ–°è§„æ·±åº¦è§£è¯»éƒ½ä¼šé¦–å‘äºæ­¤ã€‚
          url: https://www.splitshire.com/
        - name: æ•°æ®ä¿¡ä»»ä¸æ²»ç†
          description: åŒ—ç†å·¥æ´ªå»¶é’è€å¸ˆå‚ä¸çš„å¦ä¸€å…¬ä¼—å·ï¼Œæ¨é€è´¨é‡ä¹Ÿéå¸¸é«˜ã€‚
        - name: æ¸…åå¤§å­¦æ™ºèƒ½æ³•æ²»ç ”ç©¶é™¢
          description: æ¸…åå¤§å­¦æ³•å­¦é™¢è®¡ç®—æ³•å­¦ç›¸å…³çš„æˆæœéƒ½ä¼šå‘è¡¨äºæ­¤ã€‚ä¹Ÿæœ‰ä¸€äº›ç”±åœ¨è¯»åŒå­¦å®Œæˆéå¸¸æœ‰æ·±åº¦çš„æ–‡çŒ®ç»¼è¿°ã€‚
        - name: æ•°æ®æ³•å¾‹èµ„è®¯
          description: åæ”¿äº’è”ç½‘æ³•æ²»ç ”ç©¶é™¢çš„å·ï¼Œå®šæœŸä¼šå‘å¸ƒåŸŸå†…å¤–çš„æ•°æ®èµ„è®¯ã€‚
        - name: æ•°å­—ç»æµä¸ç¤¾ä¼š
          description: å¯¹å¤–ç»è´¸å¤§å­¦è®¸å¯è€å¸ˆå›¢é˜Ÿçš„å…¬ä¼—å·ï¼Œç›¸å…³å­¦æœ¯è®ºæ–‡å’ŒåŸŸå†…å¤–æ•°æ®æ³•å¾‹åŠ¨æ€å‡ä¼šæ›´æ–°ã€‚
        - name: ç§‘æŠ€åˆ©ç»´å¦
          description: ææ±¶é¾™è€å¸ˆçš„å…¬ä¼—å·ï¼Œè§£è¯»æ–‡ç« å¾ˆæœ‰ä¸ªäººé£æ ¼ï¼Œå€¼å¾—çè—ã€‚
        - name: ç½‘ç»œè¥¿ä¸œ
          description: äººå¤§çš„ä¸æ™“ä¸œè€å¸ˆåŠåŒå­¦ä»¬è¿è¥ï¼Œä¸»è¦å…³æ³¨åŸŸå¤–æ³•ï¼Œä¼šåšå¾ˆå¤šæ•°æ®æ³•ç›¸å…³çš„ç¿»è¯‘å’Œæ–‡çŒ®ç»¼è¿°ï¼Œè´¨é‡éå¸¸é«˜ã€‚
        - name: å°è´è¯´å®‰å…¨
          description: å·¦æ™“æ ‹è€å¸ˆçš„å…¬ä¼—å·ã€‚å¯¹å¾ˆå¤šå®˜æ–¹æ–‡ä»¶ã€æ ‡å‡†çš„é‡Šä¹‰éå¸¸å‡†ç¡®ã€‚
    - name: å®‰å…¨ç±»å…¬ä¼—å·æ¨è
      sites:
        - name: å®‰å…¨å°é£ä¾ 
          description: è‘—åç½‘ç»œå®‰å…¨çº¢è“å¯¹æŠ—ä¸“å®¶ã€å®‰å…¨é—­é—¨ä¼šè®®Security Practice Summitå‘èµ·äººã€‚
        - name: é¸Ÿå“¥è°ˆäº‘å®‰å…¨
          description: è‘—åç™½å¸½å­cnbirdï¼Œå®‰å…¨åœˆè€äººã€èµ„æ·±å®‰å…¨ä¸“å®¶ï¼Œå¯¹äº‘å®‰å…¨æœ‰æ·±å…¥ç ”ç©¶ã€‚
        - name: å›å“¥çš„ä½“å†
          description: èµ„æ·±å®‰å…¨ä¸“å®¶ï¼Œå¯¹ä¼ä¸šå®‰å…¨ä½“ç³»å»ºè®¾ç‰¹åˆ«æ˜¯é‡‘èè¡Œä¸šçš„å®‰å…¨ä½“ç³»ç»éªŒä¸°å¯Œã€‚
        - name: çš®ç›¸
          description: åœˆå†…è€å‰è¾ˆã€å®‰å…¨ç„¦ç‚¹æ ¸å¿ƒæˆå‘˜ã€è…¾è®¯å®‰å…¨ç„æ­¦å®éªŒå®¤è´Ÿè´£äººtombkeeperã€‚
        - name: å…œå“¥å¸¦ä½ å­¦å®‰å…¨
          description: æ—¢æ‡‚ç½‘ç»œå®‰å…¨åˆæ‡‚AIçš„å¤§ä½¬ï¼Œå¯¹AIåº”ç”¨åˆ°å®‰å…¨é¢†åŸŸæœ‰å¾ˆæ·±å…¥çš„ç ”ç©¶
        - name: èµ›åšæ”»é˜²æ‚Ÿé“
          description: å®‰å…¨åœˆè€äººã€80SECæˆå‘˜ã€èµ„æ·±ç™½å¸½å­rayh4cçš„å…¬ä¼—å·
        - name: å´é²åŠ 
          description: è€ä¸€è¾ˆé»‘å®¢ã€å®‰å…¨ç„¦ç‚¹çš„æ ¸å¿ƒæˆå‘˜quackï¼Œç½‘ç»œå®‰å…¨ç»éªŒä¸°å¯Œï¼Œåˆ›ç«‹äº†å®‰å…¨å…¬å¸å¤§æˆå¤©ä¸‹ã€‚
        - name: Ms08067å®‰å…¨å®éªŒå®¤
          description: åŒ—äº¬äº¤é€šå¤§å­¦å®‰å…¨ç ”ç©¶å‘˜ï¼Œå…¬ä¼—å·æ–‡ç« æŠ€æœ¯å®æˆ˜å±…å¤šï¼Œéå¸¸é€‚åˆå¹´è½»äººå­¦ä¹ ã€‚
        - name: æ‡’äººåœ¨æ€è€ƒ
          description: ã€ŠWebå‰ç«¯é»‘å®¢æŠ€æœ¯æ­ç§˜ã€‹ä½œè€…ã€å®‰å…¨åœˆè€äººä½™å¼¦çš„å…¬ä¼—å·ã€‚
        - name: é’±å¡˜é—¨å¤–çš„äº’è”ç½‘æ•£ä¿®
          description: flyh4tçš„å…¬ä¼—å·ï¼Œè‘—åç™½å¸½å­ã€TSRCç¬¬ä¸‰ä»»è´Ÿè´£äººã€‚
        - name: æ¼æ´æˆ˜äº‰
          description: ã€Šæ¼æ´æˆ˜äº‰ï¼šè½¯ä»¶æ¼æ´åˆ†æç²¾è¦ã€‹ä½œè€…riuskskçš„å…¬ä¼—å·ã€‚
        - name: å…¨é¢‘å¸¦é˜»å¡å¹²æ‰°
          description: RC2åçªƒå¯†å®éªŒå®¤è´Ÿè´£äººã€ZerOneæ— çº¿å®‰å…¨å›¢é˜Ÿåˆ›å§‹äººã€ã€Šæ— çº¿ç½‘ç»œæ”»é˜²å®æˆ˜ã€‹ç³»åˆ—ä¹¦ç±ä½œè€…Longasæ¨å”çš„å…¬ä¼—å·ã€‚
    - name: å…¶ä»–å…¬ä¼—å·æ¨è
      sites:
        - name: è´¢ç»Eæ³•
          description: ã€Šè´¢ç»ã€‹æ•°æ®åˆè§„ç›¸å…³çš„æ–°é—»æŠ¥é“ã€‚
        - name: éšç§æŠ¤å«é˜Ÿ
          description: ã€Šå—æ–¹éƒ½å¸‚æŠ¥ã€‹å…³äºéšç§ä¿æŠ¤ä¸“é—¨çš„å…¬ä¼—å·ã€‚
        - name: ç‚¼çŸ³ç½‘ç»œ
          description: å‡ ä¹å¯ä»¥è¯´æ˜¯ä¸šå†…æœ€å·ï¼Œè´¨é‡æœ€é«˜çš„æ•°æ®åˆè§„é•¿å›¾ã€PPTåˆ¶ä½œå…¬ä¼—å·ã€‚
        - name: å®‰çŸ¥è®¯
          description: é‡‘èæœºæ„ç›¸å…³çš„ç½‘ç»œã€æ•°æ®å®‰å…¨èµ„è®¯ã€‚
